<a href="https://colab.research.google.com/github/gauravjha201/Natural-Language-Processing/blob/main/Spam_ham_classification_Project_Using_NLTK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
from IPython.display import display

# Set seed for reproducibility

def generate_email_text(label):
    if label == 'Spam':
        spam_phrases = [
            "Win money now! Click here to claim your prize.",
            "URGENT: Your account has been compromised. Verify your details.",
            "Congratulations! You've won a free iPhone. Claim it today.",
            "Limited time offer: Cheap meds available at a discount.",
            "Lowest price guaranteed for weight loss supplements. Buy now!"
        ]
        return np.random.choice(spam_phrases)
    else: # Ham
        ham_phrases = [
            "Hello, how are you doing today?",
            "Let's have lunch tomorrow at 1 PM.",
            "Meeting scheduled for 3 PM. Agenda attached.",
            "Project deadline reminder for next Friday.",
            "See you at the conference next week."
        ]
        return np.random.choice(ham_phrases)

# Generate 5000 synthetic emails
data = []
for i in range(1, 5001):
    label = np.random.choice(['Spam', 'Ham'], p=[0.5, 0.5]) # 50/50 split for now
    email_text = generate_email_text(label)
    data.append([i, email_text, label])

# Create DataFrame
messages_df = pd.DataFrame(data, columns=['Email ID', 'Email Text', 'Label'])

print(f"Generated dataset with {len(messages_df)} rows.")
display(messages_df.head())

Generated dataset with 5000 rows.


,Email ID,Email Text,Label
0,1,Congratulations! You've won a free iPhone. Cla...,Spam
1,2,Lowest price guaranteed for weight loss supple...,Spam
2,3,Project deadline reminder for next Friday.,Ham
3,4,Limited time offer: Cheap meds available at a ...,Spam
4,5,Limited time offer: Cheap meds available at a ...,Spam


In [16]:
messages=messages_df.drop('Email ID',axis=1)
messages.head()

,Email Text,Label
0,Congratulations! You've won a free iPhone. Cla...,Spam
1,Lowest price guaranteed for weight loss supple...,Spam
2,Project deadline reminder for next Friday.,Ham
3,Limited time offer: Cheap meds available at a ...,Spam
4,Limited time offer: Cheap meds available at a ...,Spam


In [17]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [20]:
corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['Email Text'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)



In [21]:
corpus[]

['congratul free iphon claim today',
 'lowest price guarante weight loss supplement buy',
 'project deadlin remind next friday',
 'limit time offer cheap med avail discount',
 'limit time offer cheap med avail discount',
 'lowest price guarante weight loss supplement buy',
 'lowest price guarante weight loss supplement buy',
 'meet schedul pm agenda attach',
 'limit time offer cheap med avail discount',
 'win money click claim prize',
 'let lunch tomorrow pm',
 'urgent account compromis verifi detail',
 'meet schedul pm agenda attach',
 'hello today',
 'limit time offer cheap med avail discount',
 'hello today',
 'meet schedul pm agenda attach',
 'hello today',
 'win money click claim prize',
 'congratul free iphon claim today',
 'see confer next week',
 'urgent account compromis verifi detail',
 'congratul free iphon claim today',
 'see confer next week',
 'lowest price guarante weight loss supplement buy',
 'see confer next week',
 'see confer next week',
 'lowest price guarante weig

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()

In [23]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))

print(X)



[[0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 ... 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 ... 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 ... 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 ... 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 ... 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 ... 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0

In [24]:
cv.vocabulary_

{'congratul': np.int64(19),
 'free': np.int64(25),
 'iphon': np.int64(32),
 'claim': np.int64(10),
 'today': np.int64(72),
 'congratul free': np.int64(20),
 'free iphon': np.int64(26),
 'iphon claim': np.int64(33),
 'claim today': np.int64(12),
 'lowest': np.int64(40),
 'price': np.int64(57),
 'guarante': np.int64(28),
 'weight': np.int64(80),
 'loss': np.int64(38),
 'supplement': np.int64(68),
 'buy': np.int64(7),
 'lowest price': np.int64(41),
 'price guarante': np.int64(58),
 'guarante weight': np.int64(29),
 'weight loss': np.int64(81),
 'loss supplement': np.int64(39),
 'supplement buy': np.int64(69),
 'project': np.int64(60),
 'deadlin': np.int64(21),
 'remind': np.int64(62),
 'next': np.int64(50),
 'friday': np.int64(27),
 'project deadlin': np.int64(61),
 'deadlin remind': np.int64(22),
 'remind next': np.int64(63),
 'next friday': np.int64(51),
 'limit': np.int64(36),
 'time': np.int64(70),
 'offer': np.int64(53),
 'cheap': np.int64(8),
 'med': np.int64(44),
 'avail': np.int64

In [31]:
# Output feature
y=pd.get_dummies(messages['Label'])
y

,Ham,Spam
0,False,True
1,False,True
2,True,False
3,False,True
4,False,True
...,...,...
4995,True,False
4996,False,True
4997,False,True
4998,False,True


In [32]:
# Recreate y as a DataFrame to ensure .iloc works correctly
y = pd.get_dummies(messages['Label'])
# Select the 'Spam' column as the target variable
y = y['Spam'].values

In [33]:
y

array([ True,  True, False,  True,  True,  True,  True, False,  True,  True, False,  True, False, False,  True, False, False, False,  True,  True, False,  True,  True, False,  True, False, False,  True,  True,  True, ..., False,  True, False,  True,  True,  True,  True, False,  True, False, False,  True,  True, False,  True, False, False,  True,  True, False,  True, False, False,  True,  True, False,  True,  True,  True, False])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [35]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(x_train,y_train)


In [36]:
spam_detect_model

MultinomialNB()

In [38]:
y_pred=spam_detect_model.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_m=confusion_matrix(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(confusion_m)
print(acc)
print(report)


[[515   0]
 [  0 485]]
1.0
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       515
        True       1.00      1.00      1.00       485

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

