<a href="https://colab.research.google.com/github/gauravjha201/Natural-Language-Processing/blob/main/Spam_ham_classification_Project_Using_Tf_Idf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

# Set seed for reproducibility

def generate_email_text(label):
    if label == 'Spam':
        spam_phrases = [
            "Win money now! Click here to claim your prize.",
            "URGENT: Your account has been compromised. Verify your details.",
            "Congratulations! You've won a free iPhone. Claim it today.",
            "Limited time offer: Cheap meds available at a discount.",
            "Lowest price guaranteed for weight loss supplements. Buy now!"
        ]
        return np.random.choice(spam_phrases)
    else: # Ham
        ham_phrases = [
            "Hello, how are you doing today?",
            "Let's have lunch tomorrow at 1 PM.",
            "Meeting scheduled for 3 PM. Agenda attached.",
            "Project deadline reminder for next Friday.",
            "See you at the conference next week."
        ]
        return np.random.choice(ham_phrases)

# Generate 5000 synthetic emails
data = []
for i in range(1, 5001):
    label = np.random.choice(['Spam', 'Ham'], p=[0.5, 0.5]) # 50/50 split for now
    email_text = generate_email_text(label)
    data.append([i, email_text, label])

# Create DataFrame
messages_df = pd.DataFrame(data, columns=['Email ID', 'Email Text', 'Label'])

print(f"Generated dataset with {len(messages_df)} rows.")
display(messages_df.head())

Generated dataset with 5000 rows.


,Email ID,Email Text,Label
0,1,Project deadline reminder for next Friday.,Ham
1,2,Lowest price guaranteed for weight loss supple...,Spam
2,3,See you at the conference next week.,Ham
3,4,See you at the conference next week.,Ham
4,5,Project deadline reminder for next Friday.,Ham


In [2]:
messages=messages_df.drop('Email ID',axis=1)
messages.head()

,Email Text,Label
0,Project deadline reminder for next Friday.,Ham
1,Lowest price guaranteed for weight loss supple...,Spam
2,See you at the conference next week.,Ham
3,See you at the conference next week.,Ham
4,Project deadline reminder for next Friday.,Ham


In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [4]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['Email Text'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)



In [7]:
corpus

['project deadlin remind next friday',
 'lowest price guarante weight loss supplement buy',
 'see confer next week',
 'see confer next week',
 'project deadlin remind next friday',
 'let lunch tomorrow pm',
 'win money click claim prize',
 'congratul free iphon claim today',
 'urgent account compromis verifi detail',
 'project deadlin remind next friday',
 'let lunch tomorrow pm',
 'win money click claim prize',
 'see confer next week',
 'congratul free iphon claim today',
 'urgent account compromis verifi detail',
 'let lunch tomorrow pm',
 'see confer next week',
 'see confer next week',
 'see confer next week',
 'limit time offer cheap med avail discount',
 'congratul free iphon claim today',
 'project deadlin remind next friday',
 'project deadlin remind next friday',
 'hello today',
 'win money click claim prize',
 'urgent account compromis verifi detail',
 'win money click claim prize',
 'meet schedul pm agenda attach',
 'see confer next week',
 'see confer next week',
 'meet sch

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tv.fit_transform(corpus).toarray()



In [9]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.2773501 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.34080531,
        0.34080531],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [10]:
tv.vocabulary_

{'project': np.int64(60),
 'deadlin': np.int64(21),
 'remind': np.int64(62),
 'next': np.int64(50),
 'friday': np.int64(27),
 'project deadlin': np.int64(61),
 'deadlin remind': np.int64(22),
 'remind next': np.int64(63),
 'next friday': np.int64(51),
 'lowest': np.int64(40),
 'price': np.int64(57),
 'guarante': np.int64(28),
 'weight': np.int64(80),
 'loss': np.int64(38),
 'supplement': np.int64(68),
 'buy': np.int64(7),
 'lowest price': np.int64(41),
 'price guarante': np.int64(58),
 'guarante weight': np.int64(29),
 'weight loss': np.int64(81),
 'loss supplement': np.int64(39),
 'supplement buy': np.int64(69),
 'see': np.int64(66),
 'confer': np.int64(17),
 'week': np.int64(79),
 'see confer': np.int64(67),
 'confer next': np.int64(18),
 'next week': np.int64(52),
 'let': np.int64(34),
 'lunch': np.int64(42),
 'tomorrow': np.int64(73),
 'pm': np.int64(55),
 'let lunch': np.int64(35),
 'lunch tomorrow': np.int64(43),
 'tomorrow pm': np.int64(74),
 'win': np.int64(82),
 'money': np.in

In [11]:
y=pd.get_dummies(messages['Label'])
y

,Ham,Spam
0,True,False
1,False,True
2,True,False
3,True,False
4,True,False
...,...,...
4995,True,False
4996,True,False
4997,False,True
4998,True,False


In [18]:
y = pd.get_dummies(messages['Label'])
y = y['Spam'].values
y

array([False,  True, False, ...,  True, False, False])

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [23]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_tfidf_model=MultinomialNB().fit(x_train,y_train)


In [25]:
spam_detect_tfidf_model

MultinomialNB()

In [26]:
y_pred=spam_detect_tfidf_model.predict(x_test)


In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(cm)
print(acc)
print(report)

[[479   0]
 [  0 521]]
1.0
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       479
        True       1.00      1.00      1.00       521

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

